version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jdwitten/vagary-web:latest
    env_file:
      - ./env/api-prod.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    networks:
      - vagarynet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - vagarynet
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  vagarynet:
