version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jdwitten/vagary-web:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    depends_on:
      - db
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
  db:
    image: mysql:8.0.2
    restart: always
    environment:
      MYSQL_DATABASE: vagarydb
      MYSQL_ROOT_PASSWORD: P@11word
    ports:
      - "3308:3306"
