branch-defaults:
  master:
    environment: VagaryWeb-env
    group_suffix: null
global:
  application_name: vagary-web
  branch: null
  default_ec2_keyname: magic-secret-key-goes-here
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
