version: 2
jobs:
  build:
    docker:
      - image: 959526929918.dkr.ecr.us-east-2.amazonaws.com/vagary-web
        aws_auth:
          aws_access_key_id: AKIAIRB6V7DBZIMUTF4A
          aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
    steps:
      - run:
          name: "Every Day Tests"
          command: "testing...."
      - run:
          name: "Deploy to Staging Infrastructure"
          command: "something something darkside.... cli"
  deploy:
    docker:
      - image: 959526929918.dkr.ecr.us-east-2.amazonaws.com/vagary-web
        aws_auth:
          aws_access_key_id: AKIAIRB6V7DBZIMUTF4A
          aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
    steps:
      - run:
          name: "Full Test Suite"
          command: "testing...."
      - run:
          name: "Deploy to Production Infrastructure"
          command: "something something darkside.... cli"

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d{4}\.\d+$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d{4}\.\d+$/
