version: 2
jobs:
  build:
    docker:
      - image: 959526929918.dkr.ecr.us-east-2.amazonaws.com/vagary-web
        aws_auth:
          aws_access_key_id: AKIAIRB6V7DBZIMUTF4A
          aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
  deploy:
    docker:
      - image: 959526929918.dkr.ecr.us-east-2.amazonaws.com/vagary-web
        aws_auth:
          aws_access_key_id: AKIAIRB6V7DBZIMUTF4A
          aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d{4}\.\d+$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d{4}\.\d+$/
